const MAX_WIDTH = '6xl';
const COLOR_TEXT_PRIMARY = '#333333';
const COLOR_BORDER_DEFAULT = '#5f6062';
const COLOR_BG_HOVER = '#e2e8f0';
const CHART_AXIS_FONT_SIZE = 12;

export { MAX_WIDTH, COLOR_TEXT_PRIMARY, COLOR_BORDER_DEFAULT, COLOR_BG_HOVER, CHART_AXIS_FONT_SIZE };
